<?php
/**
 * @category NoGlitchYo
 * @package NoGlitchYo_GoogleRecaptcha  
 * @author Maxime ELOMARI <maxime.elomari@gmail.com>
 * @copyright Copyright (c) 2015, Maxime Elomari
 * @license http://creativecommons.org/licenses/by/4.0 Creative Common BY 4.0
 */
?>
<?php
/** @var $this NoGlitchYo_GoogleRecaptcha_Block_Widget */
?>
<script type="text/javascript">
    var onloadCallback = function() {
        grecaptcha.render('g_recaptcha', {
           'sitekey' : '<?php echo $this->getKey() ?>'
        });
    };
</script>
<div id="g_recaptcha"></div>
